"""add_forex_ml_models

Revision ID: 45a6e82edefc
Revises: 14e5d2bfe6f6
Create Date: 2026-07-18 17:35:12.416040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a6e82edefc'
down_revision: Union[str, Sequence[str], None] = '14e5d2bfe6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex_ml_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('active_version_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_auto_retrain', sa.Integer(), nullable=True),
    sa.Column('retrain_interval_hours', sa.Integer(), nullable=True),
    sa.Column('data_lookback_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_version_id'], ['forex_model_versions.id'], name='fk_forex_active_version_id', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_ml_models_id'), 'forex_ml_models', ['id'], unique=False)
    op.create_index(op.f('ix_forex_ml_models_name'), 'forex_ml_models', ['name'], unique=False)
    op.create_table('forex_model_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('version', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'READY', 'ERROR', name='forexmodelstatus'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('explainability', sa.JSON(), nullable=True),
    sa.Column('dataset_path', sa.String(), nullable=True),
    sa.Column('metadata_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['forex_ml_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_model_versions_id'), 'forex_model_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forex_model_versions_id'), table_name='forex_model_versions')
    op.drop_table('forex_model_versions')
    op.drop_index(op.f('ix_forex_ml_models_name'), table_name='forex_ml_models')
    op.drop_index(op.f('ix_forex_ml_models_id'), table_name='forex_ml_models')
    op.drop_table('forex_ml_models')
    # ### end Alembic commands ###
