"""add model_versions columns

Revision ID: 8d402fd5d244
Revises: abcd1234efgh
Create Date: 2026-05-09 07:14:50.289614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d402fd5d244'
down_revision: Union[str, Sequence[str], None] = 'abcd1234efgh'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('f1_score', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('latency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'latency')
    op.drop_column('model_versions', 'f1_score')
    op.drop_column('model_versions', 'accuracy')
    # ### end Alembic commands ###
