"""Add TokenUnlockEvent

Revision ID: d8f3bb936460
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-16 08:17:37.379922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f3bb936460'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('put_call_ratio', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_sentiment_id'), 'option_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_option_sentiment_symbol'), 'option_sentiment', ['symbol'], unique=False)
    op.create_table('option_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('option_type', sa.String(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_trades_id'), 'option_trades', ['id'], unique=False)
    op.create_index(op.f('ix_option_trades_ticker'), 'option_trades', ['ticker'], unique=False)
    op.create_table('token_unlock_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('token_name', sa.String(), nullable=True),
    sa.Column('unlock_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('circulating_supply_pct', sa.Float(), nullable=True),
    sa.Column('vesting_schedule', sa.JSON(), nullable=True),
    sa.Column('allocations', sa.JSON(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_unlock_events_id'), 'token_unlock_events', ['id'], unique=False)
    op.create_index(op.f('ix_token_unlock_events_symbol'), 'token_unlock_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_token_unlock_events_unlock_date'), 'token_unlock_events', ['unlock_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_unlock_events_unlock_date'), table_name='token_unlock_events')
    op.drop_index(op.f('ix_token_unlock_events_symbol'), table_name='token_unlock_events')
    op.drop_index(op.f('ix_token_unlock_events_id'), table_name='token_unlock_events')
    op.drop_table('token_unlock_events')
    op.drop_index(op.f('ix_option_trades_ticker'), table_name='option_trades')
    op.drop_index(op.f('ix_option_trades_id'), table_name='option_trades')
    op.drop_table('option_trades')
    op.drop_index(op.f('ix_option_sentiment_symbol'), table_name='option_sentiment')
    op.drop_index(op.f('ix_option_sentiment_id'), table_name='option_sentiment')
    op.drop_table('option_sentiment')
    # ### end Alembic commands ###
